name: Build and Deploy to Azure Web App - Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout code
      uses: actions/checkout@v4

    - name: 🔐 Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS2 }}

    - name: 🔨 Build Docker image
      run: docker build . -t kspoornesh/flagkpg-app

    - name: 🔐 Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🚀 Push image to Docker Hub
      run: docker push kspoornesh/flagkpg-app

    - name: 🌐 Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: poorneshflaskapp123
        images: kspoornesh/flagkpg-app
