version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"  # Azure expects host port 80
    environment:
      DB_HOST: db
      DB_NAME: flaskdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
